name: Bingo
version: 1.0
main: de.amin.bingo.BingoPlugin
authors: [ Duckulus ]
description: Bingo
api-version: 1.18
depend: [PlaceholderAPI]
commands:
  reroll:
    aliases:
      - rr
    description: rerolls board
    permission: bingo.reroll
