# The hour you want it to reset daily (HH:mm)
Date: "12:00"

# <Amount>[...(<amount> INGERIDIENT) > <amount> REWARD]

Villagers:
   "madenci":
      Name: "§bMADENCİ"
      Location: "world, 170, 70, 0, 0, 0"
      Recipes:
         - 8[4 EMERALD > 8 IRON_INGOT]
#   "oduncu":
#   "gezgin":
#   "çoban":
#   "çiftçi":
#   "simyacı":
#   "avcı":
#   "balıkçı":
#   "inşaatcı":