###################
#Bingo By Duckulus# "CHANGED/FORKED"AhmetDinc
###################

# The Current Config Version. DO NOT CHANGE OR THINGS WILL BREAK
configVersion: 1.0

# The hour you want it to reset daily (HH:mm)
Date: "12:00"

Item:
   name: "&e&lBİNGO!"
   lore:
     - "&7Eşyaları &bdikey, yatay"
     - "&bve çarpraz&7 elde et,"
     - "&7bu kağıdı ödüle çevir!"
     - ""
     - "&fÖdüller:"
     - "&8- &ex16 Zümrüt"
     - ""
     - "♦ &cAlmak için &8(Sağ tıkla)"
   
Messages:
   1: "Zaten bir bingon var... (Bir cheste koymuş olabilirsin.)"
   2: "24 saatte sadece 1 bingo alabilirsin"
   3: "... Envanterin dolu."
